name: readthedocs
dependencies:
  - python=3.9
  - conda-forge::gfortran=11.2.0
  - numpy>=1.22.2
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - pip>=21.2.4
  - pip:
    - sphinx-book-theme==0.2.0
    - sphinx-panels==0.6.0
    - nbsphinx==0.8.8
    - sphinx-togglebutton==0.3.0
    - myst-nb==0.13.2
    - sphinx-gallery==0.10.1
    - pypandoc==1.7.5
    - sphinxcontrib-mermaid==0.7.1
    - sphinxemoji==0.2.0
